name: First workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Primer Steps - Hello manu!
        run: echo "Hello!!!! from [${{ github.workflow }}] triggered by the [${{ github.event_name }}] done by [${{ github.actor }}]"

      - name: 😊 Segundo Steps
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Esta genial!"
          echo "Done!"