name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Paso-1

        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        run: echo "Hello world!!" from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-        

